### ISSUE TITLE
Carthage dependancies with sub projects

### ISSUE THREAD

**Issue by Reedyuk** [OpenShelter/fastlane-plugin-rome#16]
Hi,
Currently i have the dependancy **apollographql/apollo-ios** the issue i have is that when you fetch this dependancy, it has several targets(which build frameworks) that are required to be built to allow the full library to work.
For example, it should create Apollo.framework, ApolloSQLite.framework & ApolloWebSocket.framework

The issue i have when using rome, the cache doesnt store all of these frameworks and i am unsure how to include them.

Thoughts on how i do this? there is other popular projects too, like realm, this has several target frameworks which are required to be built and cached.

**Comment by tmspzz** [comment]
Please refer to the README in Rome's repository, under "Multiple Aliases" : https://github.com/tmspzz/Rome#multiple-aliases
