### ISSUE TITLE
meet_minimum_version function returns false negative

### ISSUE THREAD

**Issue by piellarda** [OpenShelter/fastlane-plugin-rome#9]
https://github.com/OpenShelter/fastlane-plugin-rome/blob/3dc5afd868556b1506d02fd46e1b21d3320d6b75/lib/fastlane/plugin/rome/actions/rome_action.rb#L46

It's comparing each part of the version until one if inferior so:
0.13.1.35 - minimum
0.18.0.51 - current
This for example returns false.

**Comment by tmspzz** [comment]
Good point. This seems wrong, thanks for reporting!

**Comment by tmspzz** [comment]
@piellarda this should be fixed in [0.3.5](https://rubygems.org/gems/fastlane-plugin-rome/versions/0.3.5)
